language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
before_script:
  - npm prune
script:
  - npm test
after_success:
  - ./node_modules/.bin/codecov
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
# branches:
#  except:
#   - /^v\d+\.\d+\.\d+$/
